### ISSUE TITLE
no layout ?

### ISSUE THREAD

**Issue by TanguyOrtegat** [kevingorman1000/OpenCAD#5]
I did try again teh sciprt, but there is no layout at all, looked for reparing it bu did not manage to fix it ...
![image](https://user-images.githubusercontent.com/17274032/61010278-eb8e8d80-a375-11e9-90ac-83c404fb5c3c.png)

**Comment by kevingorman1000** [comment]
Hello,

This is a common issue when it comes to the layout... The reason that it'll be doing this is due to your "BASE_URL" within the oc-config.php. I'd suggest opening up "oc-config" and looking for "BASE_URL". You will need to edit it so it reads `define('BASE_URL', '//94.23.57.43/OpenCAD');`

Hopefully this fixed your issue.

**Comment by phillf** [comment]
I would reccomend grabbing the latest version from the Stormlight Tech fork as it patches a known security flaw in 0.2.6 and earlier.

https://github.com/StormlightTech/OpenCAD-php/archive/0.3.0-HF7-1903d259.zip

**Comment by kevingorman1000** [comment]
I agree with Phil, this version is now outdated due to release 0.3.0 that was recently realised by Stormlight Tech. I'll be updating the read me.
